export const leadsDefaultValue = {
  phone: '',
  firstName: '',
  lastName: '',
  email: '',
  checkboxAddress: '',
  customerAddress: '',
  customerCity: '',
  customerState: '',
  customerZip: '',
  date: '',
  scope: '',
  address: '',
  city: '',
  state: '',
  zip: ''
}
export const userDefaultValue = {
  name: '',
  email: '',
  username: '',
  phone: '',
  password: ''
}
export const workOrderDefaultValue = {
  latitude: '',
  longitude: '',
  finishDate: '',
  startDate: '',
  workOrder: '',
  description: '',
  image: '',
  title: '',
  address: '',
  date: '',
  leadlocation: null
}
export const contractDefaultValue = {
  contractorName: '',
  logo: '',
  contractorPhone: '',
  contractorAddress: '',
  contractorEmail: '',
  contractorCity: '',
  contractorState: '',
  contractorZip: '',
  contacts: '',
  gaf: 'false',
  gafCertifications: [],
  gafRating: '',
  gafReviews: '',
  certineed: 'false',
  certineedCertifications: [],
  certineedRating: '',
  certineedReviews: '',
  owensCoring: 'false',
  owensCoringCertifications: [],
  owensCoringRating: '',
  owensCoringReviews: '',
  leadScore: '50',
  qualifiedContractorFormStarted: '',
  qualifiedContractorFormSubmitted: '',
  qualifiedContractorFormApproove: '',
  leadCompleteScore: '',
  leadSource: '',
  status: 'new',
  contractorRegion: [],
  notes: ''
}
